---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/Applications/arrs/bazarr:/config
      - /mnt/MediaData/MediaCenter/Anime:/mnt/Anime
      - /mnt/MediaData/MediaCenter/Series:/mnt/Series
      - /mnt/MediaData/MediaCenter/Movies:/mnt/Movies
    ports:
      - 6767:6767
    restart: unless-stopped