---
services:
  radarr:
    labels:
      - traefik.http.routers.radarr.rule=Host(`radarr.vkiedrowski.de`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls.certresolver=cfdns
      - traefik.enable=true
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/Applications/arrs/radarr:/config
      - /mnt/MediaData/MediaCenter/Movies:/mnt/Movies
      - /mnt/Applications/DownloaderFiles:/mnt/Downloads
    ports:
      - 7878:7878
    restart: unless-stopped