---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/Applications/arrs/radarr:/config
      - /mnt/MediaData/MediaCenter/Movies:/movies #optional
      - /mnt/Applications/DownloaderFiles:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped