version: "3.8"
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    labels:
      traefik.http.routers.karakeep.rule: "Host(`karakeep.vkiedrowski.de`)"
      traefik.http.routers.karakeep.entrypoints: "websecure"
      traefik.http.routers.karakeep.tls.certresolver: "generic"
      traefik.enable: "true"
    restart: unless-stopped
    volumes:
      - data:/data
    env_file:
      - .env
    environment:
      NEXTAUTH_URL: https://karakeep.vkiedrowski.de
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data # DON'T CHANGE THIS
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Applications/apps/karakeep/meilisearch
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Applications/apps/karakeep/data