services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local.vkiedrowski.de`)"
      - "traefik.http.routers.traefik.tls.domains[0].main=vkiedrowski.de"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.vkiedrowski.de"
      - "traefik.http.routers.traefik.tls.domains[1].main=local.vkiedrowski.de"
      - "traefik.http.routers.traefik.tls.domains[1].sans=*.local.vkiedrowski.de"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=cfdns"
      - "traefik.http.routers.traefik.service=noop@internal"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/mnt/config/externalServices.yaml"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesResolvers.cfdns.acme.dnsChallenge=true"
      - "--certificatesResolvers.cfdns.acme.dnsChallenge.provider=cloudflare"
      - "--certificatesResolvers.cfdns.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53,8.8.8.8:53"
      - "--certificatesResolvers.cfdns.acme.email=cert@vkiedrowski.de"
      - "--certificatesResolvers.cfdns.acme.storage=/mnt/config/letsencrypt/acme-dns.json"
      - "--certificatesResolvers.generic.acme.email=cert@vkiedrowski.de"
      - "--certificatesResolvers.generic.acme.storage=/mnt/config/letsencrypt/acme-http.json"
      - "--certificatesResolvers.generic.acme.httpChallenge.entryPoint=web"
    env_file:
      - .env
    ports:
      # HTTP port
      - "9080:80"
      # HTTPS Port
      - "9443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/Applications/traefik:/mnt/config
  cloudflare-companion:
    image: ghcr.io/tiredofit/docker-traefik-cloudflare-companion:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TIMEZONE=Europe/Berlin

      - LOG_TYPE=CONSOLE
      - LOG_LEVEL=INFO

      - TRAEFIK_VERSION=2
      - RC_TYPE=CNAME

      - CF_TOKEN=${CF_DNS_API_TOKEN}

      - TARGET_DOMAIN=vkiedrowski.de
      - REFRESH_ENTRIES=TRUE

      - ENABLE_TRAEFIK_POLL=TRUE
      - TRAEFIK_POLL_URL=http://reverse-proxy:8080
      - TRAEFIK_FILTER_LABEL=traefik.constraint
      - TRAEFIK_FILTER=proxy-public

      - DOMAIN1=vkiedrowski.de
      - DOMAIN1_ZONE_ID=${ZONE_ID}
      - DOMAIN1_PROXIED=TRUE
    restart: always