---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    labels:
      - traefik.http.routers.sabnzb.rule=Host(`sabnzb.vkiedrowski.de`)
      - traefik.http.routers.sabnzb.entrypoints=websecure
      - traefik.http.routers.sabnzb.tls.certresolver=cfdns
      - traefik.enable=true
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/Applications/nzb/sabnzbd/config:/config
      - /mnt/Applications/DownloaderFiles/downloads:/downloads
      - /mnt/Applications/DownloaderFiles/incomplete:/incomplete-downloads
    ports:
      - 8181:8080
    restart: unless-stopped
networks:
  default:
    name: traefik_default
    external: true