---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=Etc/UTC
    volumes:
      - /mnt/Applications/arrs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
networks:
  default:
    name: traefik_default
    external: true