---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/Applications/arrs/readarr:/config
      - /mnt/MediaData/MediaCenter/Books:/mnt/Books
      - /mnt/Applications/DownloaderFiles:/mnt/Downloads
    ports:
      - 8787:8787
    restart: unless-stopped