volumes:
  readeck-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/Applications/docker-apps/readeck/data

services:
  app:
    labels:
      traefik.http.routers.readeck.rule: "Host(`readeck.vkiedrowski.de`)"
      traefik.http.routers.readeck.entrypoints: "websecure"
      traefik.http.routers.readeck.tls.certresolver: "generic"
      traefik.docker.network: "traefik_default"
      traefik.enable: "true"
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck
    environment:
      # Defines the application log level. Can be error, warn, info, debug.
      - READECK_LOG_LEVEL=info
      # The IP address on which Readeck listens.
      - READECK_SERVER_HOST=0.0.0.0
      # The TCP port on which Readeck listens. Update container port above to match (right of colon).
      - READECK_SERVER_PORT=8000
      # Optional, the URL prefix of Readeck.
      # - READECK_SERVER_PREFIX=/
      # Optional, a list of hostnames allowed in HTTP requests.
      # - READECK_ALLOWED_HOSTS=readeck.example.com
    volumes:
      - readeck-data:/readeck
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3
    
networks:  
  default:
    name: traefik_default
    external: true  
