---
services:
  overseerr:
    labels:
      - traefik.http.routers.radarr.rule=Host(`overseerr.vkiedrowski.de`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls.certresolver=generic
      - traefik.enable=true
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=568
      - PGID=568
      - TZ=Etc/UTC
    restart: unless-stopped
networks:
  default:
    name: traefik_default
    external: true
