services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    labels:
      - traefik.http.routers.lazyl.rule=Host(`lazylibrary.vkiedrowski.de`)
      - traefik.http.routers.lazyl.entrypoints=websecure
      - traefik.http.routers.lazyl.tls.certresolver=generic
      - traefik.enable=true
    environment:
      - PUID=568
      - PGID=568
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /mnt/Applications/docker-apps/lazylibrary:/config
      - /mnt/MediaData/MediaCenter/Books/books:/mnt/Books/
      - /mnt/MediaData/MediaCenter/Books/audiobooks:/mnt/Audiobooks
      - /mnt/Applications/DownloaderFiles/downloads:/downloads
    ports:
      - 5299:5299
    restart: unless-stopped
  audiobookshelf:
    environment:
      - PUID=568
      - PGID=568
      - TZ=Etc/UTC
    labels:
      - traefik.http.routers.abs.rule=Host(`bookshelf.vkiedrowski.de`)
      - traefik.http.routers.abs.entrypoints=websecure
      - traefik.http.routers.abs.tls.certresolver=generic
      - traefik.enable=true
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:13378
    volumes:
      - /mnt/MediaData/MediaCenter/Books/audiobooks:/audiobooks
      - /mnt/MediaData/MediaCenter/Books/podcasts:/podcasts
      - /mnt/MediaData/MediaCenter/Books/metadata:/metadata
      - /mnt/Applications/docker-apps/audiobookshelf/config:/config
    restart: unless-stopped
    user: 568:568
networks:
   default:
     name: traefik_default
     external: true