---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/Applications/arrs/radarr:/config
      - /mnt/MediaData/MediaCenter/Anime:/anime
      - /mnt/MediaData/MediaCenter/Series:/series
      - /mnt/Applications/DownloaderFiles:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped