---
services:
  sonarr:
    labels:
      - traefik.http.routers.sonarr.rule=Host(`sonarr.vkiedrowski.de`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.tls.certresolver=cfdns
      - traefik.enable=true
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=568
      - PGID=568
      - TZ=Etc/UTC
    volumes:
      - /mnt/Applications/arrs/sonarr:/config
      - /mnt/MediaData/MediaCenter/Anime:/mnt/Anime
      - /mnt/MediaData/MediaCenter/Series:/mnt/Series
      - /mnt/Applications/DownloaderFiles:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

networks:
  default:
    name: traefik_default
    external: true